name: "Setup Turborepo Cache"
description: "Configures Turborepo caching using GitHub Actions cache"
runs:
  using: "composite"
  steps:
    - name: Setup Turborepo cache
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-
