name: Multicache

on:
  workflow_dispatch:

jobs:
  create-cache:
    name: Create cache
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [a, b, c]
    steps:
      - name: Make artifact
        run: |
          mkdir -p ./artifacts
          echo "This is a cache for package ${{ matrix.package }}" > ./artifacts/cache-${{ matrix.package }}.txt

      - name: Upload artifact
        uses: actions/cache/save@v4
        with:
          path: artifacts
          key: artifacts

  read-cache:
    name: Read cache
    runs-on: ubuntu-latest
    needs: create-cache
    steps:
      - name: Download artifact
        uses: actions/cache/restore@v4
        with:
          path: artifacts
          key: artifacts

      - name: List artifacts
        run: ls -la artifacts
