name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # Validate PR title and description
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert

  # Check code formatting and linting
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and Cache
        uses: ./.github/actions/setup-node-cache

      - name: Check TypeScript compilation
        run: yarn turbo build --dry-run

      - name: Check package.json format
        run: |
          for package in packages/*/package.json; do
            echo "Checking $package"
            # Verify package.json structure
            node -e "
              const pkg = require('./$package');
              if (!pkg.name.startsWith('@monorepo/')) {
                console.error('Package name must be scoped under @monorepo');
                process.exit(1);
              }
              if (pkg.private !== true) {
                console.error('Package must be private');
                process.exit(1);
              }
              if (pkg.type !== 'module') {
                console.error('Package must have type: module');
                process.exit(1);
              }
              if (!pkg.scripts || !pkg.scripts.build || !pkg.scripts.test) {
                console.error('Package must have build and test scripts');
                process.exit(1);
              }
            "
          done

  # Size impact analysis
  size-analysis:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js and Cache
        uses: ./.github/actions/setup-node-cache

      - name: Build packages
        run: yarn turbo build

      - name: Analyze bundle size
        run: |
          echo "## Bundle Size Analysis" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Package | Size |" >> $GITHUB_STEP_SUMMARY
          echo "|---------|------|" >> $GITHUB_STEP_SUMMARY

          for dist in packages/*/dist; do
            if [ -d "$dist" ]; then
              package=$(basename $(dirname "$dist"))
              size=$(du -sh "$dist" | cut -f1)
              echo "| @monorepo/$package | $size |" >> $GITHUB_STEP_SUMMARY
            fi
          done
