name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  # Build all packages for release
  build-all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [shared, a, b, c]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and Cache
        uses: ./.github/actions/setup-node-cache

      - name: Setup Turborepo Cache
        uses: ./.github/actions/setup-turborepo-cache

      - name: Run tests
        uses: ./.github/actions/run-package-tests
        with:
          package: ${{ matrix.package }}

      - name: Build package
        uses: ./.github/actions/build-package
        with:
          package: ${{ matrix.package }}

  # Create GitHub release
  release:
    runs-on: ubuntu-latest
    needs: [build-all]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
